### PR TITLE
Josh's EdgeTrak converter and GUI pull request

### PR DESCRIPTION
**Pull request by JRMeyer**

### CODE REVIEW

**Comment by myedibleenso** [comment]
@JRMeyer: 
please update your fork (see https://help.github.com/articles/syncing-a-fork/) and we'll merge in the changes.

Thanks!

**Comment by myedibleenso** [comment]
``` bash
git remote add upstream https://github.com/arizona-phonological-imaging-lab/APIL.git
git fetch upstream
git merge upstream/master
git push
```

**Comment by JRMeyer** [comment]
Hey Gus,

I missed that last push it seems when I thought I did this last night.

I just pushed now.

-josh

2015-02-10 9:15 GMT-07:00 Gustave Hahn-Powell notifications@github.com:

> git fetch upstream
> git merge upstream/master
> git push
> 
> ## 
> 
> Reply to this email directly or view it on GitHub
> https://github.com/arizona-phonological-imaging-lab/APIL/pull/3#issuecomment-73728306
> .

## 

Joshua Meyer
Ph.D. Student
Linguistics Department
University of Arizona

**Comment by myedibleenso** [comment]
Merged!

**Pull request merged**
